- name: Set kotlin vim settings
  ansible.builtin.copy:
    dest: ~/.vim/ftplugin/kotlin.vim
    mode: "0644"
    content: |
      setlocal  tabstop=4
      setlocal  shiftwidth=4

- name: Install vim plugin
  ansible.builtin.git:
    repo: https://github.com/udalov/kotlin-vim.git
    dest: ~/.vim/bundle/kotlin-vim
