- name: Install flutter
  community.general.homebrew_cask:
    name: flutter

- name: Precache
  ansible.builtin.command: flutter precache

- name: Install lcov for code coverage
  community.general.homebrew:
    name: lcov

- name: Install vim plugin
  ansible.builtin.git:
    repo: https://github.com/dart-lang/dart-vim-plugin.git
    dest: ~/.vim/bundle/dart-vim-plugin
