- name: Install jenv java environment manager
  community.general.homebrew:
    name: jenv

- name: Update .zshrc
  ansible.builtin.blockinfile:
    create: true
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR JENV"
    mode: "0644"
    block: |
      export PATH="$HOME/.jenv/bin:$PATH"
      eval "$(jenv init -)"

- name: Install current temurin
  community.general.homebrew_cask:
    name: temurin

- name: Install VisualVM
  community.general.homebrew_cask:
    name: visualvm
