- name: Install vim text editor
  community.general.homebrew:
    name: vim

- name: Setup paths for vim
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - ~/.vim/autoload
    - ~/.vim/bundle
    - ~/.vim/ftplugin

- name: Install pathogen vim plugin/configuration manager
  ansible.builtin.get_url:
    url: https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest: ~/.vim/autoload/pathogen.vim
    mode: "0644"

- name: Install vim plugin
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "~/.vim/bundle/{{ item.dest }}"
    force: true
  with_items:
    - {repo: "https://github.com/scrooloose/nerdtree.git", dest: nerdtree}
    - {repo: "https://github.com/Xuyuanp/nerdtree-git-plugin.git", dest: nerdtree-git-plugin}
    - {repo: "https://github.com/ctrlpvim/ctrlp.vim.git", dest: ctrlp}
    - {repo: "https://github.com/ntpeters/vim-better-whitespace.git", dest: vim-better-whitespace}
    - {repo: "https://github.com/airblade/vim-gitgutter.git", dest: vim-gitgutter}
    - {repo: "https://github.com/plasticboy/vim-markdown.git", dest: vim-markdown}

- name: Update .vimrc
  ansible.builtin.blockinfile:
    create: true
    path: ~/.vimrc
    marker: "\" {mark} ANSIBLE MANAGED BLOCK"
    mode: "0644"
    block: |
      execute pathogen#infect()
      syntax on
      filetype plugin indent on
      :set tabstop=2
      :set shiftwidth=2
      :set backspace=indent,eol,start
      :set expandtab
      :set nobackup
      :set noswapfile
      let g:ctrlp_map = '<c-p>'
      let g:ctrlp_cmd = 'CtrlP'
      autocmd BufEnter * EnableStripWhitespaceOnSave
      autocmd FileType Markdown setlocal spell spelllang=en_au
      set encoding=utf-8
